version: '3'
services:
    app-dev:
        build:
            context: .
            dockerfile: dockerfile
            args:
                - NODE_ENV=dev
        restart: always
        ports:
            - '5002:5002'
